### ISSUE TITLE
No module named pip with ubuntu-latest after 24.04 upgrade

### ISSUE THREAD

**Issue by devotoare** [roots/setup-trellis-cli#104]
### Version

1.3.0

### What did you expect to happen?

Action to run.

### What actually happens?

```
Initialize project
  Received 0 of 60792524 (0.0%), 0.0 MBs/sec
  Cache Size: ~58 MB (60792524 B)
  /usr/bin/tar -xf /home/runner/work/_temp/e896f1ef-f366-4829-b728-f54c647f1250/cache.tzst -P -C /home/runner/work/PROJECT/PROJECT --use-compress-program unzstd
  Received 60792524 of 60792524 (100.0%), 29.0 MBs/sec
  Cache restored successfully
  Cache restored from key: Linux-trellis-venv-17636408a8ab59ff17b82d0596d617b82c80696c64b411eb683dd[20](https://github.com/PROJECT/PROJECT/actions/runs/12264262387/job/34217933117#step:6:23)c0a89e56a
  /opt/hostedtoolcache/trellis-cli/1.13.0/x64/trellis init
  Initializing project...
  
  ⠋   Ensure pip is up to date
  [✘] Error upgrading pip
  /home/runner/work/PROJECT/PROJECT/trellis/.trellis/virtualenv/bin/python3: No module named pip
  
Error: The process '/opt/hostedtoolcache/trellis-cli/1.13.0/x64/trellis' failed with exit code 1
```

### Steps to reproduce

Run action with ubuntu-24.04 as the runner, which is now being rolled out as ubuntu-latest.

### Please confirm this isn't a support request.

Yes

**Comment by swalkinshaw** [comment]
🤔  Must be some change with Python packages in Ubuntu 24.04

I'd try two things.

1. add a task before the CLI setup with `python3 -m ensurepip`

```yml
name: Deploy site

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
    - run: python3 -m ensurepip
    - uses: roots/setup-trellis-cli@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
    - name: Deploy Production
      run: trellis deploy production
```


2. Explicitly add `setup-python` even if Python exists on Ubuntu by default:
```yaml
name: Deploy site

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
    - uses: actions/setup-python@v5
       with:
         python-version: '3.12'
    - uses: roots/setup-trellis-cli@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
    - name: Deploy Production
      run: trellis deploy production
```

You could also try some older versions of Python like 3.9 to see if that makes a difference as well.
