### ISSUE TITLE
💡 use environments for deployment

### ISSUE THREAD

**Issue by chrillep** [roots/setup-trellis-cli#73]
### Summary

nice to have to see which environment that has been deployed.

[About environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#about-environments)
Environments are used to describe a general deployment target like production, staging, or development. When a GitHub Actions workflow deploys to an environment, the environment is displayed on the main page of the repository. For more information about viewing deployments to environments, see "[Viewing deployment history](https://docs.github.com/en/actions/deployment/managing-your-deployments/viewing-deployment-history)."

**Comment by swalkinshaw** [comment]
How would this action help with environments?  I'm not too familiar with the details, but wouldn't anyone writing a job step just set the `environment`?

```yaml
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: roots/setup-trellis-cli@v1
  with:
    ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
    repo-token: ${{ secrets.GITHUB_TOKEN }}
- run: trellis deploy production
  environment: 
    name: production
    url: https://mysite.com
```

cc @MWDelaney who wrote https://github.com/MWDelaney/trellis-github-deployment which does some extra deployments integration
